require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ContacttypesController do

  # This should return the minimal set of attributes required to create a valid
  # Contacttype. As you add validations to Contacttype, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ContacttypesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all contacttypes as @contacttypes" do
      contacttype = Contacttype.create! valid_attributes
      get :index, {}, valid_session
      assigns(:contacttypes).should eq([contacttype])
    end
  end

  describe "GET show" do
    it "assigns the requested contacttype as @contacttype" do
      contacttype = Contacttype.create! valid_attributes
      get :show, {:id => contacttype.to_param}, valid_session
      assigns(:contacttype).should eq(contacttype)
    end
  end

  describe "GET new" do
    it "assigns a new contacttype as @contacttype" do
      get :new, {}, valid_session
      assigns(:contacttype).should be_a_new(Contacttype)
    end
  end

  describe "GET edit" do
    it "assigns the requested contacttype as @contacttype" do
      contacttype = Contacttype.create! valid_attributes
      get :edit, {:id => contacttype.to_param}, valid_session
      assigns(:contacttype).should eq(contacttype)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Contacttype" do
        expect {
          post :create, {:contacttype => valid_attributes}, valid_session
        }.to change(Contacttype, :count).by(1)
      end

      it "assigns a newly created contacttype as @contacttype" do
        post :create, {:contacttype => valid_attributes}, valid_session
        assigns(:contacttype).should be_a(Contacttype)
        assigns(:contacttype).should be_persisted
      end

      it "redirects to the created contacttype" do
        post :create, {:contacttype => valid_attributes}, valid_session
        response.should redirect_to(Contacttype.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved contacttype as @contacttype" do
        # Trigger the behavior that occurs when invalid params are submitted
        Contacttype.any_instance.stub(:save).and_return(false)
        post :create, {:contacttype => {}}, valid_session
        assigns(:contacttype).should be_a_new(Contacttype)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Contacttype.any_instance.stub(:save).and_return(false)
        post :create, {:contacttype => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested contacttype" do
        contacttype = Contacttype.create! valid_attributes
        # Assuming there are no other contacttypes in the database, this
        # specifies that the Contacttype created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Contacttype.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => contacttype.to_param, :contacttype => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested contacttype as @contacttype" do
        contacttype = Contacttype.create! valid_attributes
        put :update, {:id => contacttype.to_param, :contacttype => valid_attributes}, valid_session
        assigns(:contacttype).should eq(contacttype)
      end

      it "redirects to the contacttype" do
        contacttype = Contacttype.create! valid_attributes
        put :update, {:id => contacttype.to_param, :contacttype => valid_attributes}, valid_session
        response.should redirect_to(contacttype)
      end
    end

    describe "with invalid params" do
      it "assigns the contacttype as @contacttype" do
        contacttype = Contacttype.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Contacttype.any_instance.stub(:save).and_return(false)
        put :update, {:id => contacttype.to_param, :contacttype => {}}, valid_session
        assigns(:contacttype).should eq(contacttype)
      end

      it "re-renders the 'edit' template" do
        contacttype = Contacttype.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Contacttype.any_instance.stub(:save).and_return(false)
        put :update, {:id => contacttype.to_param, :contacttype => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested contacttype" do
      contacttype = Contacttype.create! valid_attributes
      expect {
        delete :destroy, {:id => contacttype.to_param}, valid_session
      }.to change(Contacttype, :count).by(-1)
    end

    it "redirects to the contacttypes list" do
      contacttype = Contacttype.create! valid_attributes
      delete :destroy, {:id => contacttype.to_param}, valid_session
      response.should redirect_to(contacttypes_url)
    end
  end

end
